
## Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

## Inputs
set_property PACKAGE_PIN V17 [get_ports {inputs0[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {inputs0[0]}]
set_property PACKAGE_PIN V16 [get_ports {inputs0[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {inputs0[1]}]
set_property PACKAGE_PIN W16 [get_ports {inputs0[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {inputs0[2]}]
set_property PACKAGE_PIN W17 [get_ports {inputs0[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {inputs0[3]}]
set_property PACKAGE_PIN W15 [get_ports {inputs1[0]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {inputs1[0]}]
set_property PACKAGE_PIN V15 [get_ports {inputs1[1]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {inputs1[1]}]
set_property PACKAGE_PIN W14 [get_ports {inputs1[2]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {inputs1[2]}]
set_property PACKAGE_PIN W13 [get_ports {inputs1[3]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {inputs1[3]}]
set_property PACKAGE_PIN V2 [get_ports {carryin}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {carryin}]
set_property PACKAGE_PIN T1 [get_ports {controls[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {controls[0]}]
set_property PACKAGE_PIN R2 [get_ports {controls[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {controls[1]}]

##output	
set_property PACKAGE_PIN W7 [get_ports {seg_out[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[0]}]
set_property PACKAGE_PIN W6 [get_ports {seg_out[1]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[1]}]
set_property PACKAGE_PIN U8 [get_ports {seg_out[2]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[2]}]
set_property PACKAGE_PIN V8 [get_ports {seg_out[3]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg_out[4]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[4]}]
set_property PACKAGE_PIN V5 [get_ports {seg_out[5]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[5]}]
set_property PACKAGE_PIN U7 [get_ports {seg_out[6]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[6]}]

set_property PACKAGE_PIN U2 [get_ports {anodes[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {anodes[0]}]
set_property PACKAGE_PIN U4 [get_ports {anodes[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {anodes[1]}]
set_property PACKAGE_PIN V4 [get_ports {anodes[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {anodes[2]}]
set_property PACKAGE_PIN W4 [get_ports {anodes[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {anodes[3]}]



